### ISSUE TITLE
what supposed to fill in the file "modules.xml"

### ISSUE THREAD

**Issue by Anda001** [SyncfusionSuccinctlyE-Books/The-Kademlia-Protocol-Succinctly#1]
I downloaded the project ,and run the demo,it always failed for lack the file "modules.xml". Have no idea about that file.

update:

I got it.

<?xml version="1.0" encoding="utf-8" ?>
<Modules>
  <Module AssemblyName='Clifton.SemanticProcessorService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpService.dll'/>
  <Module AssemblyName='FlowSharpCanvasService.dll'/>
  <Module AssemblyName='FlowSharpToolboxService.dll'/>
  <Module AssemblyName='FlowSharpMouseControllerService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpWebSocketService.dll'/>
  <Module AssemblyName='FlowSharpRestService.dll'/>

</Modules>

**Comment by wuzhenda** [comment]
I got it.

`<?xml version="1.0" encoding="utf-8" ?>
<Modules>
  <Module AssemblyName='Clifton.SemanticProcessorService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpService.dll'/>
  <Module AssemblyName='FlowSharpCanvasService.dll'/>
  <Module AssemblyName='FlowSharpToolboxService.dll'/>
  <Module AssemblyName='FlowSharpMouseControllerService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpWebSocketService.dll'/>
  <Module AssemblyName='FlowSharpRestService.dll'/>

</Modules>
`

**Comment by jmozah** [comment]
@wuzhenda How did you solve this. I am getting the same error.

**Comment by Anda001** [comment]
look into the author's repo,you will  find out .
here is the possible file.

`<?xml version="1.0" encoding="utf-8" ?>
<Modules>
  <Module AssemblyName='Clifton.SemanticProcessorService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpService.dll'/>
  <Module AssemblyName='FlowSharpCanvasService.dll'/>
  <Module AssemblyName='FlowSharpToolboxService.dll'/>
  <Module AssemblyName='FlowSharpMouseControllerService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpWebSocketService.dll'/>
  <Module AssemblyName='FlowSharpRestService.dll'/>

</Modules>
`

**Comment by wuzhenda** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<Modules>
  <Module AssemblyName='Clifton.SemanticProcessorService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpService.dll'/>
  <Module AssemblyName='FlowSharpCanvasService.dll'/>
  <Module AssemblyName='FlowSharpToolboxService.dll'/>
  <Module AssemblyName='FlowSharpMouseControllerService.dll'/>
  
  
  
  <Module AssemblyName='FlowSharpWebSocketService.dll'/>
  <Module AssemblyName='FlowSharpRestService.dll'/>

</Modules>

**Comment by Anda001** [comment]
https://gist.github.com/wuzhenda/8f621dc429eaa9a413a307414cbf913c
